#!/bin/sh

set -eu
set -x

# Create install-desktop-icons

cat > /live/persistence/TailsData_unlocked/install-desktop-icons <<EOF
#!/bin/sh

set -x

create_desktop_icons() {
  APPS="tails-documentation whisperback"

  mkdir --parents /etc/skel/Desktop

  for app in \$APPS; do
      install \
      --mode=0755 \
      "/usr/share/applications/\${app}.desktop" \
      /etc/skel/Desktop/
  done
}

send_notification() {
    sudo -u Debian-gdm sh -c ". /tmp/gdm-dbus-session-bus-address && \
                             notify-send '\$1'"
}

send_notification 'Installing Desktop icons'

dpkg -i /live/persistence/TailsData_unlocked/apt/cache/gnome-shell-extension-desktop-icons-ng*.deb && \
create_desktop_icons

if [ \$? -ne 0 ]; then
    send_notification 'Failed to install Desktop icons'
else
    send_notification 'Desktop icons installed'
fi

# Exit with 0 even if the above command failed, to avoid raising an
# exception in the Persistent Storage backend.
exit 0
EOF

chmod +x /live/persistence/TailsData_unlocked/install-desktop-icons

if ! grep -q install-desktop-icons /live/persistence/TailsData_unlocked/persistence.conf; then
  echo '/usr/local/lib/persistent-storage/on-activated-hooks/install-desktop-icons source=install-desktop-icons,file' >> /live/persistence/TailsData_unlocked/persistence.conf;
fi

# Create enable-desktop-icons.desktop

cat > /live/persistence/TailsData_unlocked/enable-desktop-icons.desktop <<EOF
[Desktop Entry]
Name=enable-desktop-icons
Exec=gnome-extensions enable ding@rastersoft.com
Type=Application
EOF

if ! grep -q enable-desktop-icons /live/persistence/TailsData_unlocked/persistence.conf; then
  echo '/etc/xdg/autostart/enable-desktop-icons.desktop	source=enable-desktop-icons.desktop,file' >> /live/persistence/TailsData_unlocked/persistence.conf;
fi
