#!/bin/bash

# Install packages from the config/patch/packages directory.
# See config/patch/packages/README.md for more information.

set -euo pipefail

# Enable xtrace with timestamp
export PS4='+ $(date "+%H:%M:%S.%3N") $(basename "${BASH_SOURCE[0]}"): '
set -x

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=../../lib/lib.sh
. "${DIR}/../../lib/lib.sh"

SCRIPT="${LIB_DIR}/install-packages"
run_with_plymouth_msg "patch: Installing packages" "${SCRIPT}"
