#!/bin/bash

# Set the root password to "root"

set -euo pipefail

# Enable xtrace with timestamp
export PS4='+ $(date "+%H:%M:%S.%3N") '
set -x

PW="root"
usermod -p "$(echo "${PW}" | mkpasswd -s)" root
