#!/bin/bash

set -euo pipefail
set -x

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=../../lib/lib.sh
. "${DIR}/../../lib/lib.sh"

SCRIPT="${LIB_DIR}/copy-new-includes"
run_with_plymouth_msg "Copying new includes" "${SCRIPT}"
