#!/bin/bash

set -euo pipefail

# Enable xtrace with timestamp
export PS4='+ $(date "+%H:%M:%S.%3N") '
set -x

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=../../lib/lib.sh
. "${DIR}/../../lib/lib.sh"

SCRIPT="${LIB_DIR}/copy-new-includes"
run_with_plymouth_msg "Copying new includes" "${SCRIPT}"
