image: debian:bookworm

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq

test-cache:
  cache:
    - key: test
      paths:
        - wiki/src/sandbox.mdwn

  script:
    - ls -al wiki/src/sandbox.mdwn
    - echo 'a' > wiki/src/sandbox.mdwn
    - ls -al wiki/src/sandbox.mdwn
