workflow:
  rules:
    - if: $CI_FORCE_RUN
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH =~ /^master|stable|testing|devel$/'
    - if: '$CI_COMMIT_BRANCH == "wip/sysadmin-16956-static-shim"'

image: debian:bookworm

variables:
    GET_SOURCES_ATTEMPTS: 10

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq

.prepare-lint-po: &prepare-lint-po
  - apt-get -qy install git i18nspector
  - git clone https://gitlab.tails.boum.org/tails/jenkins-tools.git /tmp/jenkins-tools

build-website:
  image: docker.io/zenfufu/website-builder
  cache:
    key: website-$CI_COMMIT_BRANCH
    paths:
      - config/chroot_local-includes/usr/share/doc/tails/website
      - wiki/src/.ikiwiki
      - wiki/src/**.pot
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - if: '$CI_COMMIT_BRANCH == "wip/sysadmin-16956-static-shim"'
  script:
    - echo CI_COMMIT_BRANCH = $CI_COMMIT_BRANCH
    - apt-get -qy install ikiwiki po4a libyaml-perl libyaml-libyaml-perl libyaml-syck-perl perlmagick
    - ( test -d wiki/src/.ikiwiki && ls -alh wiki/src/.ikiwiki ) || echo "No IKIWIKI cache"
    - ls -alh wiki/src/
    - ( test -d config/chroot_local-includes/usr/share/doc/tails/website && ls -alh config/chroot_local-includes/usr/share/doc/tails/website ) || echo "No WEBSITE cache"
    - ./build-website --refresh
    - apt-get install -y openssh-client rsync
    - test -e .ssh || mkdir .ssh
    - cp "$TEST_STATIC_GITLAB_SHIM_SSH_PRIVATE_KEY" .ssh/private_key
    - cp "$TEST_STATIC_GITLAB_SHIM_SSH_HOST_KEYS" .ssh/known_hosts
    - chmod 400 .ssh/known_hosts .ssh/private_key
    - echo "variables often lack a trailing newline, which breaks SSH, detect and fix"
    - ssh-keygen -y -f .ssh/private_key || echo >> .ssh/private_key
    - echo "here is the SSH key we will deploy with"
    - ssh-keygen -y -f .ssh/private_key
    - echo -n "Begin rsync to static-gitlab-shim, time is " && date '+%Y-%m-%d %H-%M-%S%z'
    - rsync --rsh="ssh -p 3004 -o UserKnownHostsFile=.ssh/known_hosts -i .ssh/private_key" --checksum --archive --no-times --verbose --mkpath --delete "config/chroot_local-includes/usr/share/doc/tails/website/" static-shim@skink.tails.boum.org:/
    - echo -n "Finished rsync to gitlab-static-shim, time is " && date '+%Y-%m-%d %H-%M-%S%z'
