# Please, make sure to only use images from `registry.gitlab.tails.boum.org`,
# as we give significant privileges to our Runners wrt. what they can do in our
# repositories.
image: registry.gitlab.tails.boum.org/sysadmin-team/container-images/debian:bookworm

variables:
    GET_SOURCES_ATTEMPTS: 10

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq

.prepare-lint-po: &prepare-lint-po
  - apt-get -qy install git i18nspector
  - git clone https://gitlab.tails.boum.org/tails/jenkins-tools.git /tmp/jenkins-tools

test-python-doctest:
  script:
    - apt-get -qy install python3 python3-sh python3-toml python3-requests python3-bs4
    - config/chroot_local-includes/usr/local/lib/tails-gdm-error-message doctest --verbose
    - env PYTHONPATH=config/chroot_local-includes/usr/lib/python3/dist-packages python3 config/chroot_local-includes/usr/local/bin/tails-documentation --doctest
    - ./bin/locale-descriptions doctest
