stages:
  - build-website

# Please, make sure to only use images from `registry.gitlab.tails.boum.org`,
# as we give significant privileges to our Runners wrt. what they can do in our
# repositories.
image: registry.gitlab.tails.boum.org/sysadmin-team/container-images/debian:bookworm

variables:
    GET_SOURCES_ATTEMPTS: 10

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -qq

.prepare-lint-po: &prepare-lint-po
  - apt-get -qy install git i18nspector
  - git clone https://gitlab.tails.boum.org/tails/jenkins-tools.git /tmp/jenkins-tools

build-website:
  stage: build-website
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - changes:
        - .gitlab-ci.yml
  image: registry.gitlab.tails.boum.org/sysadmin-team/container-images/ikiwiki:bookworm
  cache:
    key: website-$CI_COMMIT_REF_SLUG
    paths:
      - config/chroot_local-includes/usr/share/doc/tails/website
      - wiki/src/.ikiwiki
      - underlays
  artifacts:
    name: website
    paths:
      - config/chroot_local-includes/usr/share/doc/tails/website
    when: on_success
    expire_in: 1 day
  variables:
    UNDERLAYS_DIR: ${CI_PROJECT_DIR}/underlays
  script:
    - git remote -v
