#!/bin/bash

set -eu
set -o pipefail

export TEXTDOMAIN='tails'

# If we're here, it means
# config/chroot_local-includes/usr/share/initramfs-tools/scripts/lib/verify_partition_table failed. Let's
# inform the user and tell them to give us some information

REPARTITIONING_ERROR_FLAG_FILE=/var/lib/live/config/tails.disk-resize-errors

error_reason=$(cat "${REPARTITIONING_ERROR_FLAG_FILE}")

title=$(gettext 'Disk partitioning errors')

if [ "${error_reason}" = 'partitioning-corruption' ]; then
    details=$(gettext 'Something went wrong when starting your Tails USB stick for the first time: the partitioning is corrupted')
else
    details=$(gettext 'Something went wrong when starting your Tails USB stick for the first time: resizing the system partition failed')
fi

text="$(cat <<EOTEXT
$details

$(gettext 'It will be impossible to create a Persistent Storage or apply automatic upgrades.')

$(gettext 'Try to follow our instructions on <a href="%INSTALLPAGE%">installing Tails on a USB stick</a> again or use a different USB stick.' | sed -e 's@<a href="[^"]*">@<a href="https://tails.net/install">@')

$(gettext 'If you have already tried this, please send us an error report to help us solve this issue.')
EOTEXT
)"

if ! zenity \
    --question --ellipsize \
    --icon-name=error \
    --cancel-label="$(gettext 'Cancel')" \
    --ok-label="$(gettext 'Send Error Report')" \
    --title="$title" --text="$text"
then
    exit 0
fi

temp="$(mktemp)"
echo '{ "details": "Resizing system partition failed" }' > "$temp"
gtk-launch whisperback.desktop "$temp"   # whisperback will delete the file
