#!/usr/bin/env python3

import argparse
import logging
import os
from pathlib import Path

from gi.repository import Gio

import tps
import tps.logging
from tps.service import Service

logger = tps.logging.get_logger(__name__)


def main():
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--profiling", action="store_true",
                        help="Produce performance profiles in /run/tails-persistent-storage/profiles")
    args = parser.parse_args()

    tps.PROFILING = args.profiling or \
                    os.getenv("TPS_PROFILING") or \
                    "tps-profiling" in Path("/proc/cmdline").read_text().split()
    if tps.PROFILING:
        Path(tps.PROFILES_DIR).mkdir(mode=0o700, parents=True, exist_ok=True)

    # Set up logging
    debug = args.debug or \
            os.getenv("DEBUG") or \
            "debug" in Path("/proc/cmdline").read_text().split()
    log_level = logging.DEBUG if debug else logging.INFO
    log_format = "%(levelname)s:%(filename)s:%(lineno)d: %(message)s"
    logging.basicConfig(level=log_level, format=log_format)

    connection = Gio.bus_get_sync(Gio.BusType.SYSTEM)
    logger.info("Connected to the system bus")
    service = Service(connection)
    service.run()


if __name__ == '__main__':
    main()
