resource_rules:

  issues:
    rules:
      - name: Stalled WIP
        actions:
          summarize:
            destination: zen/tails
            title: "Triage stalled work-in-progress: #{Time.now.strftime('%Y-%m-%d')}"
            summary: |
              Hello, dear contributor!
              
              This is an automated process that flags issues in a ~'Doing' state
              that have not been updated since more than 3 months.
              
              If you've been mentioned in a comment below, please make sure to
              update the corresponding issue(s) in order to better reflect your
              plans, avoid too much WIP for yourself, and encourage team work.

              Please, either unassign yourself or communicate your plans
              directly in the issue, for example commenting about your planned
              time frame, replacing the "Doing" label with "To Do", or setting
              a suitable milestone.

              Thanks for contributing!

              /assign @zen
              /label ~"T:Communicate"
              /label ~"To Do"
          comment_type: thread
          comment_on_summary: |
            #{resource['assignee'].nil? ? 'TicketGardener' : ('@' + resource['assignee']['username'])}, please update the following issue: {{full_reference}}+
        conditions:
          state: opened
          labels:
            - Doing
          date:
            attribute: updated_at
            condition: older_than
            interval_type: months
            interval: 3
      - name: Stalled validation
        actions:
          summarize:
            destination: zen/tails
            title: "Triage stalled validation: #{Time.now.strftime('%Y-%m-%d')}"
            summary: |
              Hello, dear contributor!
              
              This is an automated process that flags issues in a ~'Needs validation' state
              that have not been updated since more than 45 days.
              
              If you've been mentioned in a comment below, please make sure to
              update the corresponding issue(s) in order to better reflect your
              plans, avoid too much WIP for yourself, and encourage team work.

              Please, do one of the following: 

              - If you are the author of the work that needs validation: try to
                find someone who can complete the review in a timely manner.
              - Else, if you are the reviewer, then you are currently the one
                person responsible for the work of someone else becoming
                effective or not. Because of that, please either:
                - unassign yourself to make it clear that someone else can
                  handle it, or
                - coordinate with the author of the work and organize yourself
                  to commit with a certain time frame for handling the review.

              Thanks for contributing!

              /assign @zen
              /label ~"T:Communicate"
              /label ~"To Do"
          comment_type: thread
          comment_on_summary: |
            #{resource['assignee'].nil? ? 'TicketGardener' : ('@' + resource['assignee']['username'])}, please update the following issue: {{full_reference}}+
        conditions:
          state: opened
          labels:
            - Needs Validation
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 5

  merge_requests:
    rules:
      - name: Stalled MRs
        actions:
          summarize:
            destination: zen/tails
            title: "Triage stalled merge requests: #{Time.now.strftime('%Y-%m-%d')}"
            summary: |
              Hello, dear contributor!
              
              This is an automated process that flags MRs that have not been updated since more than 45 days.
              
              If you've been mentioned in a comment below, please make sure to
              update the corresponding issue(s) in order to better reflect your
              plans, avoid too much WIP for yourself, and encourage team work.

              Please, do one of the following:
              - If you are the author of the work:
                - Unassign yourself. That's fine. If it really matters, someone
                  else, possibly you, may pick it up later.
  
                  Then, if the issue is relevant for a Tails team, bring it to
                  their attention; else, forget it and take care of yourself :)
  
              - Else, if you are the reviewer, then you are currently the one
                person responsible for the work of someone else becoming
                effective or not. Because of that, please either:
                - unassign yourself to make it clear that someone else can
                  handle it, or
                - coordinate with the author of the work and organize yourself
                  to commit with a certain time frame for handling the review.
  
              Thanks for contributing!
  
              /assign @zen
              /label ~"T:Communicate"
              /label ~"To Do"
          comment_type: thread
          comment_on_summary: |
            #{resource['assignee'].nil? ? 'TicketGardener' : ('@' + resource['assignee']['username'])}, please update the following MR: {{full_reference}}+
        conditions:
          state: opened
          draft: false
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 5
