#!/bin/sh

set -eu
set -x

echo "Fetch and install arti"

. /usr/share/tails/build/variables

# To get the URL for a new arti release binary:
# 1. Go to https://gitlab.torproject.org/tpo/core/arti/-/tags
# 2. Click the commit for the latest tag
# 3. Click the link for the report for the pipeline that ran for this commit
# 4. Click on the repro-build job
# 5. In the Job Artifacts section on the right sidebar, click Browse
# 6. Click arti-linux
# 7. Get the URL from the Download link and update ARTI_BINARY_URL
ARTI_BINARY_URL='https://gitlab.torproject.org/tpo/core/arti/-/jobs/593103/artifacts/raw/arti-linux'

# When using the vmproxy or building on jenkins we know that
# apt-cacher-ng is used, so we fetch and cache over https using the
# HTTPS/// trick.
if [ "${TAILS_PROXY_TYPE}" = 'vmproxy' ] || [ -n "${JENKINS_URL:-}" ]; then
    apt_proxy="$(apt-config --format '%v' dump Acquire::http::Proxy)"
    ARTI_BINARY_URL="$(echo "$ARTI_BINARY_URL" | sed "s@^https://@${apt_proxy}/HTTPS///@")"
    unset http_proxy HTTP_PROXY https_proxy HTTPS_PROXY
fi

cd /usr/bin
/usr/bin/curl --fail-with-body --retry 20 --output arti "${ARTI_BINARY_URL}"
if ! file --brief arti | grep -q "^ELF 64-bit LSB pie executable"; then
    echo "When fetching arti we got something else than an ELF executable" >&2
    exit 1
fi
chmod a+x arti

addgroup --system --quiet arti
adduser --system --quiet --no-create-home arti
chown -R arti:arti /etc/arti/
mkdir -p /var/lib/arti/cache /var/lib/arti/state
chown -R arti:arti /var/lib/arti
