#!/bin/sh

set -eu

echo "Fetch and install arti"

# To get the URL for a new arti release binary:
# 1. Go to https://gitlab.torproject.org/tpo/core/arti/-/tags
# 2. Click the commit for the latest tag
# 3. Click the link for the report for the pipeline that ran for this commit
# 4. Click on the repro-build job
# 5. In the Job Artifacts section on the right sidebar, click Browse
# 6. Click arti-linux
# 7. Get the URL from the Download link and update ARTI_BINARY_URL
ARTI_BINARY_URL='https://gitlab.torproject.org/tpo/core/arti/-/jobs/593103/artifacts/raw/arti-linux'

# Cache file with apt-cacher-ng
apt_proxy="$(apt-config --format '%v' dump Acquire::http::Proxy)"
if [ "${apt_proxy}" = 'http://127.0.0.1:3142' ]; then
    ARTI_BINARY_URL="$(echo "$ARTI_BINARY_URL" | sed "s@^https://@${apt_proxy}/HTTPS///@")"
    unset http_proxy HTTP_PROXY https_proxy HTTPS_PROXY
fi

cd /usr/bin
/usr/bin/curl --retry 20 --output arti "${ARTI_BINARY_URL}"
chmod a+x arti

addgroup --system --quiet arti
adduser --system --quiet --no-create-home arti
chown -R arti:arti /etc/arti/
mkdir -p /var/lib/arti/cache /var/lib/arti/state
chown -R arti:arti /var/lib/arti
