[map]
af="af_ZA"   # Afrikaans, South Africa
ar="ar:EG"
ay="ay:PE"
bg="bg_BG"   # Bulgarian, Bulgaria
bs="bs_BA"   # Bosnian, Bosnia And Herzegovina
ca="ca:ES"
cs="cs:CZ"
da="da:DK"
de="de:DE"
el="el:GR"
es=["es-MX:MX", "es-ES:ES", "es-AR:AR"]
et="et_EE"   # Estonian, Estonia
fa="fa:IR"
fi="fi:FI"
fr="fr:FR"
ga="ga-IE:IE"
gd="gd:GB"
gu="gu_IN"   # Gujarati, India
he="he:IL"
hi="hi_IN"   # Hindi, India
hr="hr_HR"   # Croatian, Croatia
hu="hu:HU"
hy="hy_AM"   # Armenian, Armenia
id="id:ID"
is="is:IS"
it="it:IT"
ja="ja:JP"
kab="kab_DZ"   # Kabyle, Algeria
ka="ka:GE"
ki="ki:KE"
kk="kk_KZ"   # Kazakh, Kazakhstan
km="km_KH"   # Central Khmer, Cambodia
kn="kn_IN"   # Kannada, India
ko="ko:KR"
lt="lt:LT"
lv="lv_LV"   # Latvian, Latvia
mk="mk:MK"
ml="ml_IN"   # Malayalam, India
mr="mr_IN"   # Marathi, India
my="my:MM"
nb="nb-NO:NO"
ne="ne_NP"   # Nepali, Nepal
nl="nl:NL"
nn="nn_NO"   # Norwegian Nynorsk, Norway
oc="oc_FR"   # Occitan (post 1500), France
or="or_IN"   # Oriya, India
pl="pl:PL"
ro="ro:RO"
ru="ru:RU"
si="si_LK"   # Sinhala, Sri Lanka
sk="sk_SK"   # Slovak, Slovakia
sl="sl_SI"   # Slovenian, Slovenia
sq="sq:AL"
sv="sv-SE:SE"
te="te_IN"   # Telugu, India
th="th:TH"
tr="tr:TR"
uk="uk:UA"
vi="vi:VN"

[extra]
# those languages are added to 
extra_languages = [
"ms:MY",
]
