[map]
ar="ar:EG"
ay="ay:PE"
ca="ca:ES"
cs="cs:CZ"
da="da:DK"
de="de:DE"
el="el:GR"
es=["es-MX:MX", "es-ES:ES", "es-AR:AR"]
fa="fa:IR"
fi="fi:FI"
fr="fr:FR"
ga="ga-IE:IE"
gd="gd:GB"
he="he:IL"
hu="hu:HU"
id="id:ID"
is="is:IS"
it="it:IT"
ja="ja:JP"
ka="ka:GE"
ki="ki:KE"
ko="ko:KR"
lt="lt:LT"
mk="mk:MK"
my="my:MM"
nb="nb-NO:NO"
nl="nl:NL"
pl="pl:PL"
ro="ro:RO"
ru="ru:RU"
sq="sq:AL"
sv="sv-SE:SE"
th="th:TH"
tr="tr:TR"
uk="uk:UA"
vi="vi:VN"
